// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14sshHitIKoHNrHmo9YA6w78b2BhOYP0',
    appId: '1:184013061272:web:5dd27476c316cf186fa4ed',
    messagingSenderId: '184013061272',
    projectId: 'foodwise-32afa',
    authDomain: 'foodwise-32afa.firebaseapp.com',
    databaseURL: 'https://foodwise-32afa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foodwise-32afa.appspot.com',
    measurementId: 'G-ZDSVJZBX6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PUva05LDzvYwkXeec3H80x1woaV9bQI',
    appId: '1:184013061272:android:34a639316b42b0b36fa4ed',
    messagingSenderId: '184013061272',
    projectId: 'foodwise-32afa',
    databaseURL: 'https://foodwise-32afa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foodwise-32afa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ0fBy7uTDW35KtofXBN2PStB2DPZ0JUg',
    appId: '1:184013061272:ios:c4a99c0d0de4429f6fa4ed',
    messagingSenderId: '184013061272',
    projectId: 'foodwise-32afa',
    databaseURL: 'https://foodwise-32afa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foodwise-32afa.appspot.com',
    iosClientId: '184013061272-rg7pdf1f8qpda230bm2sguspvsf32b1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodWise',
  );
}
