name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.11'
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./food_wise
      - name: Build iOS release
        run: flutter build ios --release --no-codesign
        working-directory: ./food_wise
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOODWISE_32AFA }}'
          channelId: live
          projectId: foodwise-32afa
